sudo: false
language: php
os:
  - linux
php:
  - 8.0
  - nightly
jobs:
  allow_failures:
  - php: nightly
before_script:
  - make setup;
script: make alone
notifications:
  email: false
branches:
  only:
  - main
