version: '3.3'
services:
  nginx-proxy:
    image: httpd-gateway
    build:
        context: ./images/nginx-proxy/
    env_file:
        - .env
        - .env.local
    environment:
      - HTTPS_METHOD=redirect
    ports:
      - '${HOST_PORT_HTTP:-80}:80'
      - '${HOST_PORT_HTTPS:-443}:443'

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/nginx/certs:/etc/nginx/certs
networks:
    default:
        external:
            name: nginx-proxy
