version: '3.9'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: httpd-gateway
    profiles:
      - "frontendProfile"
    build:
      context: ./images/nginx-proxy/
    logging:
      options:
        max-size: ${CONTAINER_DEFAULT_MAX_SIZE}
        max-file: ${CONTAINER_DEFAULT_MAX_FILE}
    env_file:
      - .env
    environment:
      - HTTPS_METHOD=noredirect
      - DEFAULT_HOST=${SERVER_DEFAULT_HOST}
    ports:
      - '${HOST_PORT_HTTP:-80}:80'
      - '${HOST_PORT_HTTPS:-443}:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/nginx/certs:/etc/nginx/certs:ro
      - $PWD/nginx/vhost.d:/etc/nginx/vhost.d
      - $PWD/nginx/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime
  whoami-public:
    image: jwilder/whoami
    profiles:
      - "frontendProfile"
    container_name: whoami-public
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=${SERVER_DEFAULT_HOST}
      - LETSENCRYPT_HOST=${SERVER_DEFAULT_HOST}
      - VIRTUAL_PORT=8000
  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: nginxproxy/acme-companion:2.1.0
    profiles:
      - "frontendProfile"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/nginx/certs:/etc/nginx/certs:rw
      - $PWD/nginx/vhost.d:/etc/nginx/vhost.d
      - $PWD/nginx/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime
    env_file:
      - .env
    logging:
      options:
        max-size: ${CONTAINER_DEFAULT_MAX_SIZE}
        max-file: ${CONTAINER_DEFAULT_MAX_FILE}
  traefik:
    image: traefik:${TRAEFIK_IMAGE_VERSION}
    container_name: traefik
    profiles:
      - "proxyProfile"
    logging:
      options:
        max-size: ${CONTAINER_DEFAULT_MAX_SIZE}
        max-file: ${CONTAINER_DEFAULT_MAX_FILE}
    restart: always
    command: --docker --docker.network=${NETWORK_GATEWAY_NAME} --docker.domain=docker.place --api=false --api.dashboard=false --docker.usebindportip=false
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=*.place
      - LETSENCRYPT_HOST=
      - VIRTUAL_PORT=80
    expose:
      - "80"
    networks:
      - backend
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/config/traefik.toml:/etc/traefik/traefik.toml
      - /etc/localtime:/etc/localtime
  whoami-backend:
    image: jwilder/whoami
    container_name: whoami-backend
    profiles:
      - "proxyProfile"
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - VIRTUAL_PORT=
    labels:
      - "traefik.web.port=8000"
      - "traefik.web.frontend.rule=Host:whoami.docker.place"
      - "traefik.web.frontend.entryPoints=http"
      - "traefik.docker.network=${NETWORK_BACKEND_NAME}"
    networks:
      - backend
networks:
  default:
    external:
      name: ${NETWORK_GATEWAY_NAME}
  backend:
    external:
      name: ${NETWORK_BACKEND_NAME}