version: '3.9'
services:
  nginx-proxy:
    extends:
      file: service-nginx-proxy.yaml
      service: serviceNginxProxy
  whoami-public:
    extends:
      file: service-whoami.yaml
      service: serviceWhoami
    profiles:
      - "frontendProfile"
    container_name: whoami-public
    environment:
      - VIRTUAL_HOST=${SERVER_DEFAULT_HOST}
      - LETSENCRYPT_HOST=${SERVER_DEFAULT_HOST}
  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: nginxproxy/acme-companion:2.1.0
    profiles:
      - "frontendProfile"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/nginx/certs:/etc/nginx/certs:rw
      - $PWD/nginx/vhost.d:/etc/nginx/vhost.d
      - $PWD/nginx/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime
    env_file:
      - .env
    logging:
      options:
        max-size: ${CONTAINER_DEFAULT_MAX_SIZE}
        max-file: ${CONTAINER_DEFAULT_MAX_FILE}
  traefik:
    extends:
      file: service-traefik.yaml
      service: serviceTraefik
    container_name: traefik
    profiles:
      - "proxyProfile"
  whoami-backend:
    extends:
      file: service-whoami.yaml
      service: serviceWhoami
    container_name: whoami-backend
    profiles:
      - "proxyProfile"
    labels:
      - "traefik.web.port=8000"
      - "traefik.web.frontend.rule=Host:whoami.docker.place"
      - "traefik.web.frontend.entryPoints=http"
      - "traefik.docker.network=${NETWORK_BACKEND_NAME}"
    networks:
      - backend
networks:
  default:
    external:
      name: ${NETWORK_GATEWAY_NAME}
  backend:
    external:
      name: ${NETWORK_BACKEND_NAME}