version: '3.3'
services:
  nginx-proxy:
    logging:
        options:
            max-size: ${CONTAINER_DEFAULT_MAX_SIZE}
            max-file: ${CONTAINER_DEFAULT_MAX_FILE}
    env_file:
        - .env
        - .env.prod
    #command: ["sh", "-c", "cat /etc/filebeat/real-filebeat.yml | sed \"s/{{LOGSTASH_SERVER}}/${LOGSTASH_SERVER}/g\" > /etc/filebeat/filebeat.yml; service filebeat start; forego start -r"]
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/nginx/certs:/etc/nginx/certs
      # - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/nginx.tmpl:/app/nginx.tmpl
      - $PWD/filebeat/real-filebeat.yml:/etc/filebeat/real-filebeat.yml
      - $PWD/bin:/app/bin
