version: '3.3'
services:
  nginx-proxy:
    image: gpupo/container-orchestration:nginx-proxy-${TAG_VERSION}
    env_file:
        - .env
        - .env.prod
    environment:
      - HTTPS_METHOD=redirect
    command: ["sh", "-c", "cat /etc/filebeat/real-filebeat.yml | sed \"s/{{LOGSTASH_SERVER}}/${LOGSTASH_SERVER}/g\" > /etc/filebeat/filebeat.yml; service filebeat start; forego start -r"]
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/nginx/certs:/etc/nginx/certs
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/nginx.tmpl:/app/nginx.tmpl
      - $PWD/filebeat/real-filebeat.yml:/etc/filebeat/real-filebeat.yml
networks:
    default:
        external:
            name: nginx-proxy
