version: '3.9'
services:
  nginx-proxy:
    extends:
      file: service-nginx-proxy.yaml
      service: serviceNginxProxy
  whoami-public:
    extends:
      file: service-whoami.yaml
      service: serviceWhoami
    profiles:
      - "frontendProfile"
    container_name: whoami-public
    environment:
      - VIRTUAL_HOST=${SERVER_DEFAULT_HOST}
      - LETSENCRYPT_HOST=${SERVER_DEFAULT_HOST}
  acme-companion:
    extends:
      file: service-acme-companion.yaml
      service: serviceAcmeCompanion
  traefik:
    extends:
      file: service-traefik.yaml
      service: serviceTraefik
    container_name: traefik
    profiles:
      - "proxyProfile"
  whoami-backend:
    extends:
      file: service-whoami.yaml
      service: serviceWhoami
    container_name: whoami-backend
    profiles:
      - "proxyProfile"
    labels:
      - "traefik.web.port=8000"
      - "traefik.web.frontend.rule=Host:whoami.docker.place"
      - "traefik.web.frontend.entryPoints=http"
      - "traefik.docker.network=${NETWORK_BACKEND_NAME}"
    networks:
      - backend
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
networks:
  default:
    external:
      name: ${NETWORK_GATEWAY_NAME}
  backend:
    external:
      name: ${NETWORK_BACKEND_NAME}