version: '3.9'
services:
  nginx-proxy:
    extends:
      file: service-nginx-proxy.yaml
      service: serviceNginxProxy
    networks:
      - default
  whoami-public:
    extends:
      file: service-whoami.yaml
      service: serviceWhoami
    profiles:
      - "frontendProfile"
    container_name: whoami-public      
    networks:
      - default  
    environment:
      - VIRTUAL_HOST=whoami.local
  whoami-ssl-public:
    extends:
      file: service-whoami.yaml
      service: serviceWhoami
    profiles:
      - "frontendProfile"
    container_name: whoami-ssl-public      
    networks:
      - default  
    environment:
      - VIRTUAL_HOST=${SERVER_DEFAULT_HOST:-whoami.yourdomain.tld}
      - LETSENCRYPT_HOST=${SERVER_DEFAULT_HOST:-whoami.yourdomain.tld}
  acme-companion:
    extends:
      file: service-acme-companion.yaml
      service: serviceAcmeCompanion
    networks:
      - default
    profiles:  
      - "frontendProfile"
  traefik:
    extends:
      file: service-traefik.yaml
      service: serviceTraefik
    container_name: traefik
    profiles:
      - "proxyProfile"
  whoami-backend:
    extends:
      file: service-whoami.yaml
      service: serviceWhoami
    container_name: whoami-backend
    profiles:
      - "proxyProfile"
    labels:
      - "traefik.web.port=8000"
      - "traefik.web.frontend.rule=Host:whoami-backend.place"
      - "traefik.web.frontend.entryPoints=http"
      - "traefik.docker.network=${NETWORK_BACKEND_NAME:-backendNetwork}"
    networks:
      - backend
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
networks:
  default:
    external:
      name: ${NETWORK_GATEWAY_NAME:-frontendNetwork}
  backend:
    external:
      name: ${NETWORK_BACKEND_NAME:-backendNetwork}