version: '3.9'
services:
  abstract-traefik:
      image: traefik:${SERVICE_TRAEFIK_TAG}
      container_name: traefik      
      logging:
        options:
          max-size: ${CONTAINER_DEFAULT_MAX_SIZE}
          max-file: ${CONTAINER_DEFAULT_MAX_FILE}
      command: --docker --logLevel="INFO" --docker.exposedByDefault=false --docker.network=backendNetwork
      expose:
        - "80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${PWD}/config/traefik.toml:/etc/traefik/traefik.toml
        - /etc/localtime:/etc/localtime