version: '3.9'
services:
  serviceTraefik:
      image: traefik:${TRAEFIK_IMAGE_VERSION:-1.7.10-alpine}
      container_name: traefik
      profiles:
        - "proxyProfile"
      logging:
        options:
          max-size: ${CONTAINER_DEFAULT_MAX_SIZE}
          max-file: ${CONTAINER_DEFAULT_MAX_FILE}
      command: --docker --docker.network=${NETWORK_GATEWAY_NAME} --docker.domain=docker.place --api=false --api.dashboard=false --docker.usebindportip=false
      env_file:
        - .env
      environment:
        - VIRTUAL_HOST=*.place
        - LETSENCRYPT_HOST=
        - VIRTUAL_PORT=80
      expose:
        - "80"
      networks:
        - backend
        - default
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${PWD}/config/traefik.toml:/etc/traefik/traefik.toml
        - /etc/localtime:/etc/localtime