version: '3.9'
services:
  serviceAcmeCompanion:
    image: nginxproxy/acme-companion:2.1.0
    profiles:
      - "backendProfile"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - $PWD/nginx/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime
    env_file:
      - .env
    logging:
      options:
        max-size: ${CONTAINER_DEFAULT_MAX_SIZE}
        max-file: ${CONTAINER_DEFAULT_MAX_FILE}