################################################################
# @see https://github.com/traefik/traefik/blob/v1.7/traefik.sample.toml
# Password: https://hostingcanada.org/htpasswd-generator/
################################################################
debug = false
logLevel = "INFO"
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.auth.basic]
    users = []

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
usebindportip = true
swarmMode = false
[api]
dashboard = false