################################################################
# @see https://github.com/traefik/traefik/blob/v1.7/traefik.sample.toml
# Password: https://hostingcanada.org/htpasswd-generator/
################################################################
[entryPoints]
  [entryPoints.http]
    [entryPoints.http.auth.basic]
    users = [
      "foo:$apr1$nfjbms6p$jsTeH8Zqkq763nm9SdDf/.", #user foo, pass bar !change!
    ]
